#!/bin/bash

if [ -z "$VAGRANT_HOME" ]; then
    export VAGRANT_HOME=~/.vagrant.d 
fi

ORIGINAL_USER=$1
ORIGINAL_BOX=$2
ORIGINAL_VERSION=$3

ATLAS_USERNAME=$4
ATLAS_BOX_NAME=$5
ATLAS_BOX_VERSION=$6

export ORIGINAL_USER=$ORIGINAL_USER
export ORIGINAL_BOX=$ORIGINAL_BOX
export ORIGINAL_VERSION=$ORIGINAL_VERSION

export ATLAS_USERNAME=$ATLAS_USERNAME
export ATLAS_BOX_NAME=$ATLAS_BOX_NAME
export ATLAS_BOX_VERSION=$ATLAS_BOX_VERSION

vagrant box add $ORIGINAL_USER/$ORIGINAL_BOX --box-version $ORIGINAL_VERSION --provider virtualbox

packer build build.json